<?php
# This file was automatically generated by the MediaWiki 1.39.6
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "orange Wiki";
$wgMetaNamespace = "Orange_Wiki";
$wgLanguageCode = "en";
$wgServer = "orangejuice.wiki";
$wgDBname = "orangejuice_wiki";


## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";
$wgScript = "{$wgScriptPath}/";
$wgUsePathInfo = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

$wgSecretKey = "3f98c9ac804e3fad9b0b306a68027b0a7e5ad07b475fb9282306906af47c1159";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "992a998b99df585f";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# End of automatically generated settings.
# Add more configuration options below.
wfLoadSkin( 'Vector' );
$wgDefaultSkin = "vector";

$wgExtraNamespaces[2300] = "Gadget";
$wgExtraNamespaces[2301] = "Gadget_talk";
$wgExtraNamespaces[2302] = "Gadget_definition";
$wgExtraNamespaces[2303] = "Gadget_definition_talk";
$wgExtraNamespaces[2900] = "Map";
$wgExtraNamespaces[2901] = "Map_talk";

# Content namespaces
$wgContentNamespaces = array_merge(
        $wgContentNamespaces,
        [ 2900 ]
);

wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';

$wgEnableUploads = true;

$wgFileExtensions = [ '.webp', '.png', '.apng', '.gif', '.JPG', '.ico', '.svg', '.ogg', '.pdf',  '.jpeg', '.jpg', '.jpe', '.jps', '.ogx', '.ogg', '.ogm', '.ogv', '.oga', '.spx', '.opus'];


wfLoadExtension( "MigrateUserAccount" );
$wgMUALogToWiki = true;
$wgMUARemoteWikiContentPath = "https://community.fandom.com/wiki/Community_Central";
$wgMUARemoteWikiAPI = "https://community.fandom.com/api.php";
$wgMUATokenSecret = "99ae70066813ed9a2d3f624cc828d7fd";
