<?php
# This file was automatically generated by the MediaWiki 1.39.6
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Tardis wiki";
$wgMetaNamespace = "Tardis_wiki";
$wgServer = "tardis.wiki";
$wgDBname = "tardis_wiki";

$wgScriptPath = "/w";       
$wgArticlePath = "/wiki/$1";
$wgScript = "{$wgScriptPath}/";
$wgUsePathInfo = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "00040ed2268b754f1bb5958d2c1a534c3084507eb5d94945b7ddff51869ac0b3";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "f87da4fce13d2870";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# End of automatically generated settings.
# Add more configuration options below.
unset( $wgFooterIcons['poweredby'] );

$wgGroupPermissions["*"]["createaccount"] = false;
$wgGroupPermissions["*"]["edit"] = false;
$wgGroupPermissions["*"]["upload"] = false;
$wgGroupPermissions["user"]["edit"] = false;
$wgGroupPermissions["user"]["upload"] = false;


$wgFileExtensions = [ '.webp', '.png', '.apng', '.gif', '.JPG', '.ico', '.svg', '.ogg', '.pdf',  '.jpeg', '.jpg', '.jpe', '.jps', '.ogx', '.ogg', '.ogm', '.ogv', '.oga', '.spx', '.opus'];

# wfLoadExtension( "MigrateUserAccount" );
$wgMUALogToWiki = true;
$wgMUARemoteWikiContentPath = "https://.fandom.com/wiki/";
$wgMUARemoteWikiAPI = "https://.fandom.com/api.php";
$wgMUATokenSecret = "";

wfLoadSkin( 'Vector' );
wfLoadSkin( 'Cosmos' );
wfLoadSkin( 'Citizen' );
wfLoadSkin( 'Timeless' );
$wgCitizenThemeDefault = "dark";


wfLoadExtension('CodeEditor');
wfLoadExtension('WikiEditor');
wfLoadExtension('Arrays');
wfLoadExtension('Variables');
wfLoadExtension('ParserFunctions');
wfLoadExtension('PortableInfobox');
wfLoadExtension('DummyFandoomMainpageTags');
wfLoadExtension('Scribunto');
wfLoadExtension( 'Gadgets' );
wfLoadExtension ('LuaCache');
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';
wfLoadExtension('ThemeToggle');
$wgThemeToggleSwitcherStyle = "dropdown";


# Extra namespaces
$wgExtraNamespaces[110] = "Forum";
$wgExtraNamespaces[111] = "Forum_talk";
$wgExtraNamespaces[112] = "Howling";
$wgExtraNamespaces[113] = "Howling_talk";
$wgExtraNamespaces[114] = "Theory";
$wgExtraNamespaces[115] = "Theory_talk";
$wgExtraNamespaces[116] = "Transmat";
$wgExtraNamespaces[117] = "Transmat_talk";
$wgExtraNamespaces[119] = "Thread_talk";
$wgExtraNamespaces[120] = "Guide";
$wgExtraNamespaces[121] = "Guide_talk";
$wgExtraNamespaces[302] = "Property";
$wgExtraNamespaces[303] = "Property_talk";
$wgExtraNamespaces[306] = "Form";
$wgExtraNamespaces[307] = "Form_talk";
$wgExtraNamespaces[308] = "Concept";
$wgExtraNamespaces[309] = "Concept_talk";
$wgExtraNamespaces[312] = "smw/schema";
$wgExtraNamespaces[313] = "smw/schema_talk";
$wgExtraNamespaces[314] = "Rule";
$wgExtraNamespaces[315] = "Rule_talk";
$wgExtraNamespaces[502] = "Blog";
$wgExtraNamespaces[828] = "Module";
$wgExtraNamespaces[829] = "Module_talk";

# Content namespaces
$wgContentNamespaces = array_merge(
	$wgContentNamespaces,
	[ 2900 ]
);



$wgEnableUploads = true;
$wgUploadDirectory = "/mnt/images/tardis-images";
$wgUploadPath = "/mnt/images/tardis-images";

wfLoadExtension( "MigrateUserAccount" );
$wgMUALogToWiki = true;
$wgMUARemoteWikiContentPath = "https://community.fandom.com/wiki/Community_Central";
$wgMUARemoteWikiAPI = "https://community.fandom.com/api.php";
$wgMUATokenSecret = "81a17543bde04cc326510a0bfc666bd0";

